### PR TITLE
Add boxes around sections

### PR DESCRIPTION
**Pull request by jasmainak**
@yousrabk what do you think of this? My choice of colors is not very good though ...

tutorial_boxes

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
I like the boxes, but yes, the color isn't good.

**Comment by jasmainak** [comment]
Excellent, I'll let you guys merge and iterate over the colors :)

**Comment by larsoner** [comment]
Agreed on both fronts, +1 for merge

Also +1 to allow whomever has been setting the colors (@yousrabk or @agramfort?) to set the colors however they want at least until the final review stages -- that would help us avoid [bike shedding](http://phk.freebsd.dk/sagas/bikeshed.html) for a while

**Comment by Eric89GXL** [comment]
Agreed on both fronts +1 for merge

Also +1 on letting whoever has been changing the colors so far (@agramfort or @yousrabk) be the only person doing it, at least until final review stages. That will help us avoid [bike shedding] (http://phk.freebsd.dk/sagas/bikeshed.html) for a while :)

**Comment by larsoner** [comment]
Sorry for the comment dup, I'll delete the second one (GitHub was being flakey)

**Comment by jasmainak** [comment]
okay merged. Thanks for the quick look :)

**Comment by agramfort** [comment]
Thx

Let's focus all on content

**Pull request merged**
